[package]
name = "qcookie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
reqwest = "0.11.22"
serde_json = "1.0.108"
thirtyfour = "0.31.0"
tokio = "1.33.0"
